version: '3.7'

services:
  postgres:
    container_name: db
    image: postgres:17
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - generate_test
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:


networks:
  generate_test:
    driver: bridge
