"""empty message

Revision ID: 856d2b553af4
Revises: 
Create Date: 2025-04-13 15:53:38.072234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856d2b553af4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('test_theme', sa.BIGINT(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=False),
    sa.Column('generation_time', sa.Integer(), nullable=False),
    sa.Column('question_num', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_bot_logs_id'), 'bot_logs', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_bot_logs_id'), table_name='bot_logs', schema='public')
    op.drop_table('bot_logs', schema='public')
    # ### end Alembic commands ###
